
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_can0, 0);

    clock_add_to_group(clock_can1, 0);

    clock_add_to_group(clock_can2, 0);

    clock_add_to_group(clock_can3, 0);

    clock_add_to_group(clock_gptmr3, 0);

    clock_add_to_group(clock_spi1, 0);

    clock_add_to_group(clock_uart0, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_usb0, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_rom, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_ptpc, 0);

    clock_add_to_group(clock_ahb, 0);

    clock_add_to_group(clock_hdma, 0);
}

void init_board_clock_source(void)
{
    /* Generate pll0 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 960000000);

    /*
     * Set PLL0CLK0 960M
     * Generate clk0_pll0 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk0, pllctlv2_div_1p0);

    /*
     * Set PLL0CLK1 600M
     * Generate clk1_pll0 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk1, pllctlv2_div_1p6);

    /*
     * Set PLL0CLK2 400M
     * Generate clk2_pll0 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk2, pllctlv2_div_2p4);

    /* Generate pll1 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);

    /*
     * Set PLL1CLK0 800M
     * Generate clk0_pll1 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk0, pllctlv2_div_1p0);

    /*
     * Set PLL1CLK1 666.667M
     * Generate clk1_pll1 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk1, pllctlv2_div_1p2);

    /*
     * Set PLL1CLK2 500M
     * Generate clk2_pll1 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk2, pllctlv2_div_1p6);

    /*
     * Set PLL1CLK3 266.667M
     * Generate clk3_pll1 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk3, pllctlv2_div_3p0);

    /*
     * Generate clk_top_cpu0 code
     * Generate clk_gpio code
     * Generate clk_usb0 code
     * Generate clk_lmm0 code
     * Generate clk_rom code
     * Generate clk_ptpc code
     * Generate clk_top_ahb0 code
     * Generate clk_hdma code
     */
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 2);

    /*
     * Set CAN0 80M
     * Generate clk_top_can0 code
     */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk0, 10);

    /*
     * Set CAN1 80M
     * Generate clk_top_can1 code
     */
    clock_set_source_divider(clock_can1, clk_src_pll1_clk0, 10);

    /*
     * Set CAN2 80M
     * Generate clk_top_can2 code
     */
    clock_set_source_divider(clock_can2, clk_src_pll1_clk0, 10);

    /*
     * Set CAN3 80M
     * Generate clk_top_can3 code
     */
    clock_set_source_divider(clock_can3, clk_src_pll1_clk0, 10);

    /*
     * Set GPTMR3 100M
     * Generate clk_top_tmr3 code
     */
    clock_set_source_divider(clock_gptmr3, clk_src_pll1_clk0, 8);

    /*
     * Set SPI1 80M
     * Generate clk_top_spi1 code
     */
    clock_set_source_divider(clock_spi1, clk_src_pll1_clk0, 10);

    /* Generate clk_top_urt0 code */
    clock_set_source_divider(clock_uart0, clk_src_pll1_clk0, 10);

    /* clk_top_xpi0 is intentionally left at the boot configuration: this image
     * executes XIP from the XPI0 NOR flash, so changing its clock source would
     * cut off the instruction fetch. */

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}
