
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#include "pinmux.h"
#include "board.h"
#include "hpm_gpio_drv.h"
#include "hpm_gpiom_drv.h"

#define SYS_LED IOC_PAD_PB10
#define CAN0_RES IOC_PAD_PB15
#define CAN1_RES IOC_PAD_PB14
#define CAN2_RES IOC_PAD_PB12
#define CAN3_RES IOC_PAD_PB11
#define BTN IOC_PAD_PA03

void init_mcan0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA01].FUNC_CTL = IOC_PA01_FUNC_CTL_MCAN0_RXD;

    HPM_IOC->PAD[IOC_PAD_PA00].FUNC_CTL = IOC_PA00_FUNC_CTL_MCAN0_TXD;
}

void init_mcan1_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA04].FUNC_CTL = IOC_PA04_FUNC_CTL_MCAN1_RXD;

    HPM_IOC->PAD[IOC_PAD_PA05].FUNC_CTL = IOC_PA05_FUNC_CTL_MCAN1_TXD;
}

void init_mcan2_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA09].FUNC_CTL = IOC_PA09_FUNC_CTL_MCAN2_RXD;

    HPM_IOC->PAD[IOC_PAD_PA08].FUNC_CTL = IOC_PA08_FUNC_CTL_MCAN2_TXD;
}

void init_mcan3_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA30].FUNC_CTL = IOC_PA30_FUNC_CTL_MCAN3_RXD;

    HPM_IOC->PAD[IOC_PAD_PA31].FUNC_CTL = IOC_PA31_FUNC_CTL_MCAN3_TXD;
}

void init_led0_pins(void)
{
    HPM_IOC->PAD[SYS_LED].FUNC_CTL = IOC_PB10_FUNC_CTL_GPIO_B_10;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 10, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 10, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 10);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 10, 0);
}

void init_gpio_pins(void)
{
    HPM_IOC->PAD[CAN0_RES].FUNC_CTL = IOC_PB15_FUNC_CTL_GPIO_B_15;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 15, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 15, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 15);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 15, 0);

    HPM_IOC->PAD[CAN1_RES].FUNC_CTL = IOC_PB14_FUNC_CTL_GPIO_B_14;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 14, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 14, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 14);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 14, 0);

    HPM_IOC->PAD[CAN2_RES].FUNC_CTL = IOC_PB12_FUNC_CTL_GPIO_B_12;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 12, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 12, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 12);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 12, 0);

    HPM_IOC->PAD[CAN3_RES].FUNC_CTL = IOC_PB11_FUNC_CTL_GPIO_B_11;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 11, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 11, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 11);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 11, 0);

    HPM_IOC->PAD[BTN].FUNC_CTL = IOC_PA03_FUNC_CTL_GPIO_A_03;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 3, gpiom_core0_fast);
    gpio_set_pin_input(HPM_FGPIO, GPIO_OE_GPIOA, 3);
}

void init_spi1_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA29].FUNC_CTL = IOC_PA29_FUNC_CTL_SPI1_MOSI;
}

void init_gptmr_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA29].FUNC_CTL = IOC_PA29_FUNC_CTL_GPTMR3_COMP_3;
}

void init_uart0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PY01].FUNC_CTL = IOC_PY01_FUNC_CTL_UART0_RXD;
    HPM_PIOC->PAD[IOC_PAD_PY01].FUNC_CTL = PIOC_PY01_FUNC_CTL_SOC_GPIO_Y_01;

    HPM_IOC->PAD[IOC_PAD_PY00].FUNC_CTL = IOC_PY00_FUNC_CTL_UART0_TXD;
    HPM_PIOC->PAD[IOC_PAD_PY00].FUNC_CTL = PIOC_PY00_FUNC_CTL_SOC_GPIO_Y_00;
}

void init_usb0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA25].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;

    HPM_IOC->PAD[IOC_PAD_PA24].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;
}
