
/*
 * Copyright (c) 2025 hpmicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * 
 * 
 * Automatically generated by HPM Pinmux Tool at Thu, 03 Apr 2025 23:22:38 GMT
 * 
 * 
 */

 #ifndef HPM_CLOCK_H
 #define HPM_CLOCK_H
 #ifdef __cplusplus
 extern "C" {
 #endif
 
 void init_adc0_clock(void);
 void init_ahb_clock(void);
 void init_gptmr0_clock(void);
 void init_spi1_clock(void);
 void init_spi2_clock(void);
 void init_uart0_clock(void);
 void init_uart2_clock(void);
 void init_gpio_clock(void);
 
 #ifdef __cplusplus
 }
 #endif
 #endif /* HPM_CLOCK_H */