
/*
 * Copyright (c) 2025 hpmicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * 
 * 
 * Automatically generated by HPM Pinmux Tool at Thu, 03 Apr 2025 23:09:19 GMT
 * 
 * 
 */

 #include "clock.h"
 #include "hpm_soc.h"
 #include "hpm_clock_drv.h"
 #include "hpm_pllctlv2_drv.h"
 
 
 void init_adc0_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     /* Generate clk_top_adc0 code */
     clock_set_adc_source(clock_adc0, clk_adc_src_ahb0);
     clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 2);
 
     clock_add_to_group(clock_adc0, 0);
 
 }
 
 void init_ahb_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     /* Generate clk_top_ahb0 code */
     clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 2);
 
     clock_add_to_group(clock_ahb, 0);
 
 }
 
 void init_gptmr0_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     clock_set_source_divider(clock_gptmr0, clk_src_pll1_clk0, 8);
 
     clock_add_to_group(clock_gptmr0, 0);
 
 }
 
 void init_spi1_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     clock_set_source_divider(clock_spi1, clk_src_pll1_clk0, 10);
 
     clock_add_to_group(clock_spi1, 0);
 
 }
 
 void init_spi2_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     clock_set_source_divider(clock_spi2, clk_src_pll1_clk0, 10);
 
     clock_add_to_group(clock_spi2, 0);
 
 }
 
 void init_uart0_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     clock_set_source_divider(clock_uart0, clk_src_pll1_clk0, 10);
 
     clock_add_to_group(clock_uart0, 0);
 
 }
 
 void init_uart2_clock(void)
 {
     /* Generate pll0 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);
 
     /* Generate clk0_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);
 
     /* Generate clk1_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);
 
     /* Generate clk2_pll0 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);
 
     /* Generate pll1 code */
     pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);
 
     /* Generate clk0_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);
 
     /* Generate clk1_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);
 
     /* Generate clk2_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);
 
     /* Generate clk3_pll1 code */
     pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);
 
     clock_set_source_divider(clock_uart2, clk_src_pll1_clk0, 10);
 
     clock_add_to_group(clock_uart2, 0);
 
 }

 void init_gpio_clock(void)
 {
    /* Generate pll0 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 30, 0);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 0, 0);

    /* Generate clk1_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 1, 1);

    /* Generate clk2_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 2, 4);

    /* Generate pll1 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);

    /* Generate clk0_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 0, 0);

    /* Generate clk1_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 1, 1);

    /* Generate clk2_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 2, 3);

    /* Generate clk3_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 3, 10);

    clock_add_to_group(clock_gpio, 0);
 }
 