
/*
 * Copyright (c) 2025 hpmicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool at Thu, 03 Apr 2025 23:38:39 GMT
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

 #include "board.h"
#include "pinmux.h"
#include "hpm_gpio_drv.h"
#include "hpm_gpiom_drv.h"

#define TCK_SPI2_CLK IOC_PAD_PB11
#define TDO_SPI2_MISO IOC_PAD_PB12
#define TDI_SPI2_MOSI IOC_PAD_PB13
#define TRST IOC_PAD_PB14
#define SRST IOC_PAD_PB15
#define SRST_IN IOC_PAD_PB09
#define TMS_O_SPI1_MOSI IOC_PAD_PA29
#define TMS_I_SPI1_MISO IOC_PAD_PA28
#define LED0 IOC_PAD_PY00
#define LED1 IOC_PAD_PY01
#define PWM_REF IOC_PAD_PA10
#define SPI1_CLK IOC_PAD_PA27
#define USB_DM IOC_PAD_PA25
#define USB_DP IOC_PAD_PA24
#define SWD_DIO_DIR IOC_PAD_PA30

void init_adc_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PB08].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;
}


void init_py_pins_as_pgpio(void) {
  /* Set PY00-PY05 default function to PGPIO */
  HPM_PIOC->PAD[IOC_PAD_PY00].FUNC_CTL = PIOC_PY00_FUNC_CTL_PGPIO_Y_00;
  HPM_PIOC->PAD[IOC_PAD_PY01].FUNC_CTL = PIOC_PY01_FUNC_CTL_PGPIO_Y_01;
  HPM_PIOC->PAD[IOC_PAD_PY02].FUNC_CTL = PIOC_PY02_FUNC_CTL_PGPIO_Y_02;
  HPM_PIOC->PAD[IOC_PAD_PY03].FUNC_CTL = PIOC_PY03_FUNC_CTL_PGPIO_Y_03;
  HPM_PIOC->PAD[IOC_PAD_PY04].FUNC_CTL = PIOC_PY04_FUNC_CTL_PGPIO_Y_04;
  HPM_PIOC->PAD[IOC_PAD_PY05].FUNC_CTL = PIOC_PY05_FUNC_CTL_PGPIO_Y_05;
}

void init_gpio_swj_pins(void)
{
    HPM_IOC->PAD[SRST_IN].FUNC_CTL = IOC_PB09_FUNC_CTL_GPIO_B_09;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 9, gpiom_core0_fast);
    gpio_set_pin_input(HPM_FGPIO, GPIO_OE_GPIOB,9);

    HPM_IOC->PAD[TCK_SPI2_CLK].FUNC_CTL = IOC_PB11_FUNC_CTL_GPIO_B_11;
    HPM_IOC->PAD[TCK_SPI2_CLK].PAD_CTL = IOC_PAD_PAD_CTL_SR_SET(1)|IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 11, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 11);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 11, 1);

    HPM_IOC->PAD[TDO_SPI2_MISO].FUNC_CTL = IOC_PB12_FUNC_CTL_GPIO_B_12;
    HPM_IOC->PAD[TDO_SPI2_MISO].PAD_CTL =  IOC_PAD_PAD_CTL_SR_SET(1)|IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 12, gpiom_core0_fast);
    gpio_set_pin_input(HPM_FGPIO, GPIO_OE_GPIOB, 12);

    HPM_IOC->PAD[TDI_SPI2_MOSI].FUNC_CTL = IOC_PB13_FUNC_CTL_GPIO_B_13;
    HPM_IOC->PAD[TDI_SPI2_MOSI].PAD_CTL =  IOC_PAD_PAD_CTL_SR_SET(1)|IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 13, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 13);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 13, 1);

    HPM_IOC->PAD[TRST].FUNC_CTL = IOC_PB14_FUNC_CTL_GPIO_B_14;
    HPM_IOC->PAD[TRST].PAD_CTL =  IOC_PAD_PAD_CTL_SR_SET(1)|IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 14, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 14);
    gpio_write_pin(HPM_FGPIO, GPIO_OE_GPIOB, 14, 1);

    HPM_IOC->PAD[SRST].FUNC_CTL = IOC_PB15_FUNC_CTL_GPIO_B_15;
    HPM_IOC->PAD[SRST].PAD_CTL =  IOC_PAD_PAD_CTL_SR_SET(1)|IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 15, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 15);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 15, 0);

    HPM_IOC->PAD[TMS_O_SPI1_MOSI].FUNC_CTL = IOC_PA29_FUNC_CTL_GPIO_A_29;
    HPM_IOC->PAD[TMS_O_SPI1_MOSI].PAD_CTL =  IOC_PAD_PAD_CTL_SR_SET(1)|IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 29, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 29);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 29, 0);

    HPM_IOC->PAD[TMS_I_SPI1_MISO].FUNC_CTL = IOC_PA28_FUNC_CTL_GPIO_A_28;
    HPM_IOC->PAD[TMS_I_SPI1_MISO].PAD_CTL = IOC_PAD_PAD_CTL_PE_SET(0) | IOC_PAD_PAD_CTL_OD_SET(0);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 28, gpiom_core0_fast);
    gpio_set_pin_input(HPM_FGPIO, GPIO_OE_GPIOA, 28);

    HPM_IOC->PAD[SWD_DIO_DIR].FUNC_CTL = IOC_PA30_FUNC_CTL_GPIO_A_30;
    HPM_IOC->PAD[SWD_DIO_DIR].PAD_CTL = IOC_PAD_PAD_CTL_SPD_SET(3);

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 30, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 30);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 30, 1);
}

void init_gpio_pins(void)
{
    /* Button (PA03): assign to GPIO0, pull-down, schmitt trigger */
    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 3, gpiom_soc_gpio0);
    uint32_t pad_ctl = IOC_PAD_PAD_CTL_PE_SET(1) | IOC_PAD_PAD_CTL_PS_SET(0) | IOC_PAD_PAD_CTL_HYS_SET(1);
    HPM_IOC->PAD[IOC_PAD_PA03].FUNC_CTL = IOC_PA03_FUNC_CTL_GPIO_A_03;
    HPM_IOC->PAD[IOC_PAD_PA03].PAD_CTL = pad_ctl;
    gpio_set_pin_input(BOARD_APP_GPIO_CTRL, BOARD_APP_GPIO_INDEX, BOARD_APP_GPIO_PIN);
    gpio_disable_pin_interrupt(BOARD_APP_GPIO_CTRL, BOARD_APP_GPIO_INDEX, BOARD_APP_GPIO_PIN);
}

void init_jtag_pins(void) {
  HPM_IOC->PAD[IOC_PAD_PA06].FUNC_CTL = IOC_PA06_FUNC_CTL_JTAG_TCK;

  HPM_IOC->PAD[IOC_PAD_PA05].FUNC_CTL = IOC_PA05_FUNC_CTL_JTAG_TDI;

  HPM_IOC->PAD[IOC_PAD_PA04].FUNC_CTL = IOC_PA04_FUNC_CTL_JTAG_TDO;

  HPM_IOC->PAD[IOC_PAD_PA07].FUNC_CTL = IOC_PA07_FUNC_CTL_JTAG_TMS;
}

void init_led_pins(void) {
  HPM_PIOC->PAD[LED0].FUNC_CTL = PIOC_PY00_FUNC_CTL_SOC_GPIO_Y_00;
  HPM_IOC->PAD[LED0].FUNC_CTL = IOC_PY00_FUNC_CTL_GPIO_Y_00;

  gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOY, 0, gpiom_soc_gpio0);
  gpio_set_pin_output(HPM_GPIO0, GPIO_OE_GPIOY, 0);
  gpio_write_pin(HPM_GPIO0, GPIO_DO_GPIOY, 0, 1);

  HPM_PIOC->PAD[LED1].FUNC_CTL = PIOC_PY01_FUNC_CTL_SOC_GPIO_Y_01;
  HPM_IOC->PAD[LED1].FUNC_CTL = IOC_PY01_FUNC_CTL_GPIO_Y_01;

  gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOY, 1, gpiom_soc_gpio0);
  gpio_set_pin_output(HPM_GPIO0, GPIO_OE_GPIOY, 1);
  gpio_write_pin(HPM_GPIO0, GPIO_DO_GPIOY, 1, 1);
}

void init_pwm_pins(void)
{
    HPM_IOC->PAD[PWM_REF].FUNC_CTL = IOC_PA10_FUNC_CTL_GPTMR0_COMP_2;
}

void init_spi1_swd_pins(void) {
  HPM_IOC->PAD[SPI1_CLK].FUNC_CTL =
      IOC_PA27_FUNC_CTL_SPI1_SCLK | IOC_PAD_FUNC_CTL_LOOP_BACK_MASK;

  HPM_IOC->PAD[TMS_O_SPI1_MOSI].FUNC_CTL = IOC_PA29_FUNC_CTL_SPI1_MOSI;

  HPM_IOC->PAD[TMS_I_SPI1_MISO].FUNC_CTL = IOC_PA28_FUNC_CTL_SPI1_MISO;
}

void init_spi2_jtag_pins(void) {
  HPM_IOC->PAD[TCK_SPI2_CLK].FUNC_CTL =
      IOC_PB11_FUNC_CTL_SPI2_SCLK | IOC_PAD_FUNC_CTL_LOOP_BACK_MASK;

  HPM_IOC->PAD[TDI_SPI2_MOSI].FUNC_CTL = IOC_PB13_FUNC_CTL_SPI2_MOSI;

  HPM_IOC->PAD[TDO_SPI2_MISO].FUNC_CTL = IOC_PB12_FUNC_CTL_SPI2_MISO;

  HPM_IOC->PAD[TMS_I_SPI1_MISO].FUNC_CTL = IOC_PA28_FUNC_CTL_GPIO_A_28;

  gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 28, gpiom_soc_gpio0);
  gpio_set_pin_input(HPM_GPIO0, GPIO_OE_GPIOA, 28);
  gpio_disable_pin_interrupt(HPM_GPIO0, GPIO_IE_GPIOA, 28);

  HPM_IOC->PAD[TMS_O_SPI1_MOSI].FUNC_CTL = IOC_PA29_FUNC_CTL_GPIO_A_29;

  gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 29, gpiom_soc_gpio0);
  gpio_set_pin_output(HPM_GPIO0, GPIO_OE_GPIOA, 29);
  gpio_write_pin(HPM_GPIO0, GPIO_DO_GPIOA, 29, 0);
}

/* Disable UART2 pins (PA08/PA09) - configure as floating GPIO input */
void uninit_uart2_pins(void) {
    /* Configure PA08 (UART2_TXD) as floating GPIO input */
    HPM_IOC->PAD[IOC_PAD_PA08].FUNC_CTL = IOC_PA08_FUNC_CTL_GPIO_A_08;
    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 8, gpiom_soc_gpio0);
    gpio_set_pin_input(HPM_GPIO0, GPIO_OE_GPIOA, 8);
    
    /* Configure PA09 (UART2_RXD) as floating GPIO input */
    HPM_IOC->PAD[IOC_PAD_PA09].FUNC_CTL = IOC_PA09_FUNC_CTL_GPIO_A_09;
    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 9, gpiom_soc_gpio0);
    gpio_set_pin_input(HPM_GPIO0, GPIO_OE_GPIOA, 9);
}

/* Disable JTAG TDI pin (PB13) - configure as floating GPIO input */
void uninit_jtag_tdi_pin(void) {
    /* Configure PB13 (TDI/SPI2_MOSI) as floating GPIO input */
    HPM_IOC->PAD[IOC_PAD_PB13].FUNC_CTL = IOC_PB13_FUNC_CTL_GPIO_B_13;
    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 13, gpiom_soc_gpio0);
    gpio_set_pin_input(HPM_GPIO0, GPIO_OE_GPIOB, 13);
}

void init_uart_pins(UART_Type *ptr) {
    if (ptr == HPM_UART0) {
        HPM_IOC->PAD[IOC_PAD_PA01].FUNC_CTL = IOC_PA01_FUNC_CTL_UART0_RXD;
        HPM_IOC->PAD[IOC_PAD_PA00].FUNC_CTL = IOC_PA00_FUNC_CTL_UART0_TXD;
    } else if (ptr == HPM_UART2) {
        HPM_IOC->PAD[IOC_PAD_PA09].FUNC_CTL = IOC_PA09_FUNC_CTL_UART2_RXD;
        HPM_IOC->PAD[IOC_PAD_PA08].FUNC_CTL = IOC_PA08_FUNC_CTL_UART2_TXD;
    } else {
        ;
    }
}

void init_usb_pins(USB_Type *ptr) {

  (void)ptr; // Suppress unused parameter warning
  HPM_IOC->PAD[USB_DM].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;

  HPM_IOC->PAD[USB_DP].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;
}

void init_gptmr_channel_pin(GPTMR_Type *ptr, uint32_t channel, bool as_comp)
{
    if (ptr == HPM_GPTMR0) {
        if (as_comp) {
            switch (channel) {
            case 1:
                HPM_IOC->PAD[IOC_PAD_PB08].FUNC_CTL = IOC_PB08_FUNC_CTL_GPTMR0_COMP_1;
                break;
            case 2:
                HPM_IOC->PAD[IOC_PAD_PB10].FUNC_CTL = IOC_PB10_FUNC_CTL_GPTMR0_COMP_2;
                break;
            case 3:
                HPM_IOC->PAD[IOC_PAD_PB15].FUNC_CTL = IOC_PB15_FUNC_CTL_GPTMR0_COMP_3;
                break;
            default:
                break;
            }
        } else {
            if (channel == 1) {
                HPM_IOC->PAD[IOC_PAD_PB09].FUNC_CTL = IOC_PB09_FUNC_CTL_GPTMR0_CAPT_1;
            }
        }
    } else if (ptr == HPM_GPTMR1) {
        if ((as_comp == true) && (channel == 3)) {
            HPM_IOC->PAD[IOC_PAD_PB13].FUNC_CTL = IOC_PB13_FUNC_CTL_GPTMR1_COMP_3;
        }
    }
}
