
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_board_clock(void)
{
    clock_add_to_group(clock_cpu0, 0);

    clock_add_to_group(clock_ahb, 0);

    clock_add_to_group(clock_lmm0, 0);

    clock_add_to_group(clock_mchtmr0, 0);

    clock_add_to_group(clock_rom, 0);

    clock_add_to_group(clock_mot0, 0);

    clock_add_to_group(clock_gpio, 0);

    clock_add_to_group(clock_hdma, 0);

    clock_add_to_group(clock_xpi0, 0);

    clock_add_to_group(clock_ptpc, 0);
}

void init_board_clock_source(void)
{
    /* Generate pll0 code */
    pllctlv2_init_pll_with_freq(HPM_PLLCTLV2, pllctlv2_pll0, 960000000);

    /*
     * Set PLL0CLK0 960M
     * Generate clk0_pll0 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, pllctlv2_pll0, pllctlv2_clk0, pllctlv2_div_1p0);

    /*
     * Set PLL0CLK1 600M
     * Generate clk1_pll0 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, pllctlv2_pll0, pllctlv2_clk1, pllctlv2_div_1p6);

    /*
     * Set PLL0CLK2 400M
     * Generate clk2_pll0 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, pllctlv2_pll0, pllctlv2_clk2, pllctlv2_div_2p4);

    /*
     * PLL1 -> 800 MHz.
     * board_init_can_clock() sources clk_can0..3 from clk_src_pll1_clk0 / 10,
     * i.e. it expects PLL1CLK0 to be exactly 800 MHz (=> 80 MHz CAN clock).
     */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 33, 80000000);

    /*
     * Set PLL1CLK0 800M
     * Generate clk0_pll1 code
     */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk0, pllctlv2_div_1p0);

    /* Generate clk_top_mct0 code */
    clock_set_source_divider(clock_mchtmr0, clk_src_osc24m, 1);
}

void init_gptmr3_clock(void)
{
    clock_add_to_group(clock_gptmr3, 0);
}
