
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#include "hpm_uart_drv.h"
#include "hpm_usb_drv.h"
#include "hpm_mcan_drv.h"

#ifdef __cplusplus
extern "C" {
#endif

void init_mcan0_pins(void);
void init_mcan1_pins(void);
void init_mcan2_pins(void);
void init_mcan3_pins(void);
void init_led_pins(void);
void init_usb0_pins(void);
void init_uart0_pins(void);
void init_gpio_pins(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
