
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#include "pinmux.h"
#include "board.h"
#include "hpm_gpio_drv.h"
#include "hpm_gpiom_drv.h"

#define CAN0_TR IOC_PAD_PA10
#define BOOT IOC_PAD_PA03
#define CAN0_STA IOC_PAD_PA02
#define CAN1_TR IOC_PAD_PA26
#define CAN1_STA IOC_PAD_PA27
#define CAN2_TR IOC_PAD_PA28
#define CAN2_STA IOC_PAD_PB08
#define CAN3_TR IOC_PAD_PB09
#define CAN3_STA IOC_PAD_PB10

void init_mcan0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA01].FUNC_CTL = IOC_PA01_FUNC_CTL_MCAN0_RXD;

    HPM_IOC->PAD[IOC_PAD_PA00].FUNC_CTL = IOC_PA00_FUNC_CTL_MCAN0_TXD;
}

void init_mcan3_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA31].FUNC_CTL = IOC_PA31_FUNC_CTL_MCAN3_TXD;

    HPM_IOC->PAD[IOC_PAD_PA30].FUNC_CTL = IOC_PA30_FUNC_CTL_MCAN3_RXD;
}

void init_mcan2_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA08].FUNC_CTL = IOC_PA08_FUNC_CTL_MCAN2_TXD;

    HPM_IOC->PAD[IOC_PAD_PA09].FUNC_CTL = IOC_PA09_FUNC_CTL_MCAN2_RXD;
}

void init_mcan1_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA04].FUNC_CTL = IOC_PA04_FUNC_CTL_MCAN1_RXD;

    HPM_IOC->PAD[IOC_PAD_PA05].FUNC_CTL = IOC_PA05_FUNC_CTL_MCAN1_TXD;
}

void init_led_pins(void)
{
    HPM_IOC->PAD[CAN0_TR].FUNC_CTL = IOC_PA10_FUNC_CTL_GPIO_A_10;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 10, gpiom_core0_fast);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 10);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 10, 0);

    HPM_IOC->PAD[CAN0_STA].FUNC_CTL = IOC_PA02_FUNC_CTL_GPIO_A_02;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 2, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 2, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 2);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 2, 0);

    HPM_IOC->PAD[CAN1_TR].FUNC_CTL = IOC_PA26_FUNC_CTL_GPIO_A_26;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 26, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 26, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 26);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 26, 0);

    HPM_IOC->PAD[CAN1_STA].FUNC_CTL = IOC_PA27_FUNC_CTL_GPIO_A_27;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 27, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 27, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 27);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 27, 0);

    HPM_IOC->PAD[CAN2_TR].FUNC_CTL = IOC_PA28_FUNC_CTL_GPIO_A_28;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 28, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 28, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 28);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 28, 0);

    HPM_IOC->PAD[CAN2_STA].FUNC_CTL = IOC_PB08_FUNC_CTL_GPIO_B_08;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 8, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 8, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 8);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 8, 0);

    HPM_IOC->PAD[CAN3_TR].FUNC_CTL = IOC_PB09_FUNC_CTL_GPIO_B_09;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 9, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 9, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 9);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 9, 0);

    HPM_IOC->PAD[CAN3_STA].FUNC_CTL = IOC_PB10_FUNC_CTL_GPIO_B_10;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 10, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOB, 10, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOB, 10);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOB, 10, 0);
}

void init_usb0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA25].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;

    HPM_IOC->PAD[IOC_PAD_PA24].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;
}

void init_uart0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PY01].FUNC_CTL = IOC_PY01_FUNC_CTL_UART0_RXD;
    HPM_PIOC->PAD[IOC_PAD_PY01].FUNC_CTL = PIOC_PY01_FUNC_CTL_SOC_GPIO_Y_01;

    HPM_IOC->PAD[IOC_PAD_PY00].FUNC_CTL = IOC_PY00_FUNC_CTL_UART0_TXD;
    HPM_PIOC->PAD[IOC_PAD_PY00].FUNC_CTL = PIOC_PY00_FUNC_CTL_SOC_GPIO_Y_00;
}

void init_gpio_pins(void)
{
    HPM_IOC->PAD[BOOT].FUNC_CTL = IOC_PA03_FUNC_CTL_GPIO_A_03;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 3, gpiom_soc_gpio0);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 3, gpiom_core0_fast);
    gpio_set_pin_input(HPM_GPIO0, GPIO_OE_GPIOA, 3);
    gpio_disable_pin_interrupt(HPM_GPIO0, GPIO_IE_GPIOA, 3);
}
