/*
 * USB Configuration for hello_world (DFU runtime)
 */
#ifndef USB_CONFIG_H
#define USB_CONFIG_H

#include "board.h"

#define CONFIG_USB_PRINTF(...) ((void)0)
#define CONFIG_USB_DBG_LEVEL 0

#define CONFIG_USB_HS
#define CONFIG_USB_ALIGN_SIZE 4
#define USB_NOCACHE_RAM_SECTION __attribute__((section(".noncacheable")))

#define USBD_VID           0x34B7
#define USBD_PID           0x0005
#define USBD_MAX_POWER     100

#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 512
#define CONFIG_USBDEV_ADVANCE_DESC
#define CONFIG_USBDEV_MAX_BUS 1

#define CONFIG_USB_DEVICE 1
#define CONFIG_USB_DEVICE_DFU 1
#define CONFIG_USB_DEVICE_CDC_ACM 1
#define CONFIG_USB_DEVICE_MSC 1
#define CONFIG_USBDEV_MSC_MAX_LUN 1
#define CONFIG_USBDEV_MSC_MAX_BUFSIZE 512
#define CONFIG_USBDEV_MSC_MANUFACTURER_STRING ""
#define CONFIG_USBDEV_MSC_PRODUCT_STRING ""
#define CONFIG_USBDEV_MSC_VERSION_STRING ""

#define CONFIG_USBHOST_MAX_RHPORTS 1
#define CONFIG_USBHOST_MAX_EXTHUBS 1
#define CONFIG_USBHOST_MAX_EHPORTS 4
#define CONFIG_USBHOST_MAX_INTERFACES 4
#define CONFIG_USBHOST_MAX_INTF_ALTSETTINGS 1
#define CONFIG_USBHOST_MAX_ENDPOINTS 4
#define CONFIG_USBHOST_DEV_NAMELEN 32

#define CONFIG_HPM_USBD_BASE HPM_USB0_BASE
#define CONFIG_HPM_USBD_IRQn IRQn_USB0

#endif
