
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#ifndef HPM_CLOCK_H
#define HPM_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

void init_board_clock(void);
void init_board_clock_source(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_CLOCK_H */
