
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#include "pinmux.h"
#include "board.h"
#include "hpm_gpio_drv.h"
#include "hpm_gpiom_drv.h"

#define LED0 IOC_PAD_PA08
#define LED1 IOC_PAD_PA09
#define USER_BTN IOC_PAD_PA03

void init_led0_pins(void)
{
    HPM_IOC->PAD[LED0].FUNC_CTL = IOC_PA08_FUNC_CTL_GPIO_A_08;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 8, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 8, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 8);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 8, 1);
}

void init_led1_pins(void)
{
    HPM_IOC->PAD[LED1].FUNC_CTL = IOC_PA09_FUNC_CTL_GPIO_A_09;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 9, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 9, gpiom_soc_gpio0);
    gpio_set_pin_output(HPM_FGPIO, GPIO_OE_GPIOA, 9);
    gpio_write_pin(HPM_FGPIO, GPIO_DO_GPIOA, 9, 0);
}

void init_gpio_pins(void)
{
    HPM_IOC->PAD[USER_BTN].FUNC_CTL = IOC_PA03_FUNC_CTL_GPIO_A_03;

    gpiom_set_pin_controller(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 3, gpiom_core0_fast);
    gpiom_disable_pin_visibility(HPM_GPIOM, GPIOM_ASSIGN_GPIOA, 3, gpiom_soc_gpio0);
    gpio_set_pin_input(HPM_FGPIO, GPIO_OE_GPIOA, 3);
}

void init_uart0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA01].FUNC_CTL = IOC_PA01_FUNC_CTL_UART0_RXD;

    HPM_IOC->PAD[IOC_PAD_PA00].FUNC_CTL = IOC_PA00_FUNC_CTL_UART0_TXD;
}

void init_mcan2_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PY01].FUNC_CTL = IOC_PY01_FUNC_CTL_MCAN2_RXD;
    HPM_PIOC->PAD[IOC_PAD_PY01].FUNC_CTL = PIOC_PY01_FUNC_CTL_SOC_GPIO_Y_01;

    HPM_IOC->PAD[IOC_PAD_PY00].FUNC_CTL = IOC_PY00_FUNC_CTL_MCAN2_TXD;
    HPM_PIOC->PAD[IOC_PAD_PY00].FUNC_CTL = PIOC_PY00_FUNC_CTL_SOC_GPIO_Y_00;
}

void init_usb0_pins(void)
{
    HPM_IOC->PAD[IOC_PAD_PA25].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;

    HPM_IOC->PAD[IOC_PAD_PA24].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;
}
